tmdb:
  api:
    key: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhMDI5OGI1M2ZlMWIyYjBhOWIyNWQ0MTVmNzQyYWNiNSIsIm5iZiI6MTcwMDQ5MjEwOC45NjQsInN1YiI6IjY1NWI3MzRjYjU0MDAyMTRkM2NjMmViNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.GKq4SXgee2ANnhL6CUQTFqoHzKc1cDkIBfEnBnGINvg"

spring:
  application:
    name: "themovie"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=movieSpringApp;encrypt=false;trustServerCertificate=true
    username: sa
    password: l£0Ar407Eg
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.SQLServerDialect"
